# Generated by Django 2.2.7 on 2019-12-16 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Модель автомобиля')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(db_index=True, max_length=200, verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Виды услуг',
                'verbose_name_plural': 'Виды услуг',
            },
        ),
        migrations.CreateModel(
            name='Tel_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_number', models.CharField(db_index=True, max_length=30, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номер телефона',
            },
        ),
        migrations.CreateModel(
            name='Services_prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='av.Cars', verbose_name='Модель автомобиля')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='av.Services', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Услуги+цена',
                'verbose_name_plural': 'Услуги+цена',
                'ordering': ['service'],
            },
        ),
        migrations.CreateModel(
            name='Calculate_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='av.Cars', verbose_name='Модель автомобиля')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='av.Services', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Расчет стоимости',
                'verbose_name_plural': 'Расчет стоимости',
            },
        ),
    ]
