# Generated by Django 2.2.7 on 2019-12-23 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адрес',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Тип автомобиля')),
            ],
            options={
                'verbose_name': 'Тип автомобиля',
                'verbose_name_plural': 'Типы автомобилей',
                'ordering': ['car'],
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя, фамилия')),
                ('num_car', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Гос.номер автомобиля')),
                ('count', models.IntegerField(db_index=True, default=0, verbose_name='Количество моек')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['count'],
            },
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя, фамилия')),
                ('e_mail', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Номер телефона')),
                ('rating', models.CharField(db_index=True, max_length=1, verbose_name='Оценка по 5-бальной шкале')),
                ('feedback', models.TextField(db_index=True, max_length=200, verbose_name='Отзыв')),
                ('date_published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации отзыва')),
            ],
            options={
                'verbose_name': 'Отзывы об автомойке',
                'verbose_name_plural': 'Отзывы об автомойке',
                'ordering': ['date_published'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Виды услуг',
                'verbose_name_plural': 'Виды услуг',
            },
        ),
        migrations.CreateModel(
            name='Tel_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_number', models.CharField(db_index=True, max_length=50, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номер телефона',
            },
        ),
        migrations.CreateModel(
            name='Services_prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='av.Cars', verbose_name='Тип автомобиля')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='av.Services', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Услуги+цена',
                'verbose_name_plural': 'Услуги+цена',
                'ordering': ['service'],
            },
        ),
        migrations.CreateModel(
            name='Calculate_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='av.Cars', verbose_name='Модель автомобиля')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='av.Services', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Расчет стоимости',
                'verbose_name_plural': 'Расчет стоимости',
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя, фамилия')),
                ('tel', models.CharField(db_index=True, max_length=200, verbose_name='Номер телефона')),
                ('e_mail', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='E-mail')),
                ('num_car', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Гос.номер автомобиля')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации заявки')),
                ('date_service', models.DateField(db_index=True, verbose_name='Дата')),
                ('time_service', models.TimeField(db_index=True, help_text='Введите время в таком формате: 15:00', verbose_name='Время')),
                ('price', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Цена')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='av.Cars', verbose_name='Тип автомобиля')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='av.Services', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Записи на мойку',
                'verbose_name_plural': 'Записи на мойку',
                'ordering': ['-date_created'],
            },
        ),
    ]
